"""
RailwayBrain AI - TrackSentinel ML Predictor
--------------------------------------------
A genuinely TRAINED machine-learning model (RandomForestRegressor) that
learns crack-growth behaviour from multi-cycle USFD inspection histories,
and predicts the NEXT crack length for a track segment.

Why this exists alongside Paris Law:
- Paris Law  = physics theory (what SHOULD happen given material constants)
- This model = data-driven learning (what the inspection data actually shows)
A production system would train on real RDSO USFD archives; this demo
trains on clearly-labelled SYNTHETIC histories generated by the same
physics engine plus realistic noise, so the "Physics vs ML" comparison
shown in the UI is honest about its data source.

The trained model is cached at module level so training happens once per
process (fast enough for Streamlit Cloud free tier: ~600 samples,
RandomForest with 60 trees trains in well under a second).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

from backend.tracksentinel.crack_growth_model import (
    RAIL_GRADE_CONSTANTS,
    generate_synthetic_inspection_history,
    paris_law_growth_rate,
)

logger = logging.getLogger("railwaybrain.ml")

_GRADE_CODE = {g: i for i, g in enumerate(RAIL_GRADE_CONSTANTS.keys())}  # 90UTS=0, HH=1, SH=2

_MODEL: RandomForestRegressor | None = None
_MODEL_MAE: float = 0.0
_TRAIN_SAMPLES: int = 0


@dataclass
class MLPrediction:
    predicted_next_crack_mm: float     # ML forecast after +10 MGT of traffic
    physics_next_crack_mm: float       # Paris Law forecast for the same +10 MGT
    ml_growth_rate_mm_per_mgt: float   # implied by the ML forecast
    physics_growth_rate_mm_per_mgt: float
    agreement_pct: float               # how closely ML and physics agree (100 = identical)
    model_mae_mm: float                # validation error of the trained model
    training_samples: int
    verdict: str                       # human-readable comparison sentence


def _build_training_frame(n_tracks: int = 45, cycles: int = 10) -> pd.DataFrame:
    """
    Generate a corpus of synthetic multi-cycle histories across all rail
    grades, then convert each consecutive inspection pair into one
    supervised sample:
        features: [current_crack_mm, mgt_step, grade_code, prev_growth_rate]
        target:   next_crack_mm
    """
    rows = []
    for grade in RAIL_GRADE_CONSTANTS.keys():
        for t in range(n_tracks):
            hist = generate_synthetic_inspection_history(
                f"TRAIN-{grade}-{t:03d}", grade, cycles=cycles, seed=1000 + t * 7 + _GRADE_CODE[grade]
            )
            cracks = hist["crack_length_mm"].to_numpy()
            mgts = hist["mgt_cumulative"].to_numpy()
            for i in range(1, len(cracks) - 1):
                prev_rate = (cracks[i] - cracks[i - 1]) / max(mgts[i] - mgts[i - 1], 1e-6)
                rows.append({
                    "current_crack_mm": cracks[i],
                    "mgt_step": mgts[i + 1] - mgts[i],
                    "grade_code": _GRADE_CODE[grade],
                    "prev_growth_rate": prev_rate,
                    "next_crack_mm": cracks[i + 1],
                })
    return pd.DataFrame(rows)


def _ensure_model() -> None:
    """Train once per process; cache at module level."""
    global _MODEL, _MODEL_MAE, _TRAIN_SAMPLES
    if _MODEL is not None:
        return

    df = _build_training_frame()
    X = df[["current_crack_mm", "mgt_step", "grade_code", "prev_growth_rate"]].to_numpy()
    y = df["next_crack_mm"].to_numpy()

    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=60, max_depth=10, random_state=42, n_jobs=-1)
    model.fit(X_tr, y_tr)

    _MODEL = model
    _MODEL_MAE = float(mean_absolute_error(y_te, model.predict(X_te)))
    _TRAIN_SAMPLES = len(df)
    logger.info("TrackSentinel ML trained: %d samples, validation MAE=%.3f mm",
                _TRAIN_SAMPLES, _MODEL_MAE)


def model_info() -> tuple[int, float]:
    """(training_samples, validation_mae_mm) — trains on first call."""
    _ensure_model()
    return _TRAIN_SAMPLES, round(_MODEL_MAE, 3)


def predict_next_crack(current_crack_mm: float, rail_grade: str,
                        prev_growth_rate: float | None = None,
                        mgt_step: float = 10.0) -> MLPrediction:
    """
    Compare a trained-ML forecast against the Paris Law physics forecast
    for the same +mgt_step of traffic loading.
    """
    _ensure_model()
    assert _MODEL is not None

    physics_rate = paris_law_growth_rate(current_crack_mm, rail_grade)
    if prev_growth_rate is None:
        prev_growth_rate = physics_rate  # cold start: seed with physics

    features = np.array([[current_crack_mm, mgt_step,
                          _GRADE_CODE.get(rail_grade, 0), prev_growth_rate]])
    ml_next = float(_MODEL.predict(features)[0])
    ml_next = max(ml_next, current_crack_mm)  # cracks don't shrink

    physics_next = current_crack_mm + physics_rate * mgt_step
    ml_rate = (ml_next - current_crack_mm) / mgt_step

    # Agreement: 100% when identical, decays with relative difference
    denom = max(abs(physics_next - current_crack_mm), 1e-6)
    rel_diff = abs(ml_next - physics_next) / denom
    agreement = round(max(0.0, 100.0 * (1.0 - min(rel_diff, 1.0))), 1)

    if agreement >= 80:
        verdict = ("ML model and Paris Law physics closely agree — high confidence "
                   "that the growth trend is following the expected fatigue curve.")
    elif agreement >= 50:
        verdict = ("ML model sees a moderately different growth pattern than pure "
                   "physics predicts — recommend one extra confirmation USFD reading.")
    else:
        verdict = ("ML model diverges strongly from the physics baseline — this track's "
                   "data pattern is unusual. Prioritise a manual inspection to rule out "
                   "measurement error or an accelerating defect.")

    return MLPrediction(
        predicted_next_crack_mm=round(ml_next, 2),
        physics_next_crack_mm=round(physics_next, 2),
        ml_growth_rate_mm_per_mgt=round(ml_rate, 4),
        physics_growth_rate_mm_per_mgt=round(physics_rate, 4),
        agreement_pct=agreement,
        model_mae_mm=round(_MODEL_MAE, 3),
        training_samples=_TRAIN_SAMPLES,
        verdict=verdict,
    )


def fit_empirical_growth_rate(history_df: pd.DataFrame) -> float | None:
    """
    Fit the ACTUAL growth rate (mm per MGT) from a track's full run-on-run
    history via least-squares — this is the 'run-on-run analysis' promised
    in proposal IS0000000165, using every reading instead of only the latest.
    Returns None when fewer than 3 readings exist.
    """
    if len(history_df) < 3:
        return None
    x = history_df["mgt_cumulative"].to_numpy(dtype=float)
    y = history_df["crack_length_mm"].to_numpy(dtype=float)
    if np.ptp(x) < 1e-6:
        return None
    slope = float(np.polyfit(x, y, 1)[0])
    return round(max(slope, 0.0), 4)
